---
- serviceName: svc-plugins-list
  apiConfig:
    method: GET
    path: "/api/v2/plugins"
    requireAuth: true
  serviceConfig:
    environmentalVariables:
      REGION: {REGION}
      TENANT_ID: {TENANT_ID}
      TENANT_CONFIG_TABLE: {TENANT_CONFIG_TABLE}
      TENANT_CONFIG_PARTITION_KEY: {TENANT_CONFIG_PARTITION_KEY}
    lambdaConfig:
      handler: lambda_function.lambda_handler
      runtime: python
      runtimeVersion: latest
      timeout: 10
      isArm64: true
      permissions:
        requireS3: false
        requireDynamoDB: true
        requireSecretsManager: true
      layers:
        - name: svc-plugins-list-extension