version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install awscli

  pre_build:
    commands:
      - echo "Starting build process..."

  build:
    commands:
      - echo "Running CloudFormation deployment script"
      - python delta-installer.py  # Assuming your script is named deploy.py

  post_build:
    commands:
      - echo "Build completed successfully."