Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 1152
      Handler: com.paladincloud.assetsender.AssetDoneHandler::handleRequest
      CodeUri: /Users/kevintavog/Workspace/paladin/ce-extensions/assets-management/services/asset-sender
      Runtime: java21
      Architectures:
        - x86_64
      Environment:
        Variables:
          ASSET_SHIPPER_DONE_SQS_URL: https://sqs.us-east-1.amazonaws.com/194626369622/kvt-saasdev-asset-shipping-done.fifo
          AUTH_API_URL: https://paladincloudsaasdev.auth.us-east-1.amazoncognito.com
          BASE_PALADIN_CLOUD_API_URI: https://saasdev.paladincloud.io/api
          CONFIG_CREDENTIALS: dXNlcjpwYWNtYW4=
          CONFIG_URL: https://saasdev.paladincloud.io/api/config/batch/prd/latest
          JAVA_TOOL_OPTIONS: --enable-preview