---
- serviceName: svc-asset-details
  apiConfig:
    method: GET
    path: "/api/v2/assets/{assetId}"
    requireAuth: true
    requireOptionsMethod: true
  serviceConfig:
    environmentalVariables:
      ASSUME_ROLE_ARN: {ASSUME_ROLE_ARN}
      ENABLE_EXTENSION: {ENABLE_EXTENSION}
      REGION: {REGION}
      SECRET_NAME_PREFIX: {SECRET_NAME_PREFIX}
      TENANT_CONFIG_OUTPUT_TABLE: {TENANT_CONFIG_OUTPUT_TABLE}
      TENANT_PARTITION_KEY: {TENANT_PARTITION_KEY}
    lambdaConfig:
      handler: lambda_function.lambda_handler
      runtime: PYTHON_3_12
      runtimeVersion: latest
      timeout: 10
      isArm64: true
      permissions:
        requireS3: false
        requireDynamoDB: true
        requireSecretsManager: false
      layers:
        - name: asset-details-layer
---
- serviceName: svc-asset-violations
  apiConfig:
    method: GET
    path: "/api/v2/targets/{targetType}/assets/{assetId}/violations"
    requireAuth: true
    requireOptionsMethod: true
  serviceConfig:
    environmentalVariables:
      ASSUME_ROLE_ARN: {ASSUME_ROLE_ARN}
      ENABLE_EXTENSION: {ENABLE_EXTENSION}
      REGION: {REGION}
      SECRET_NAME_PREFIX: {SECRET_NAME_PREFIX}
      TENANT_CONFIG_OUTPUT_TABLE: {TENANT_CONFIG_OUTPUT_TABLE}
      TENANT_PARTITION_KEY: {TENANT_PARTITION_KEY}
    lambdaConfig:
      handler: lambda_function.lambda_handler
      runtime: python
      runtimeVersion: latest
      timeout: 10
      isArm64: true
      permissions:
        requireS3: false
        requireDynamoDB: true
        requireSecretsManager: true
      layers:
        - name: svc-asset-vioaltions-layer