---
- serviceName: svc-asset-details
  apiConfig:
    method: GET
    path: "/api/v2/assets/{assetId}"
    requireAuth: true
  serviceConfig:
    environmentalVariables:
    lambdaConfig:
      handler: lambda_function.lambda_handler
      runtime: python
      runtimeVersion: latest
      timeout: 10
      isArm64: true
      permissions:
        requireS3: false
        requireDynamoDB: true
        requireSecretsManager: true
      layers:
        - name: svc-asset-details-layer
- serviceName: svc-asset-violations
  apiConfig:
    method: GET
    path: "/api/v2/targets/{targetType}/assets/{assetId}/violations"
    requireAuth: true
  serviceConfig:
    environmentalVariables:
    lambdaConfig:
      handler: lambda_function.lambda_handler
      runtime: python
      runtimeVersion: latest
      timeout: 10
      isArm64: true
      permissions:
        requireS3: false
        requireDynamoDB: true
        requireSecretsManager: true
      layers:
        - name: svc-asset-vioaltions-layer